<?php

namespace App\DataFixtures;

use Doctrine\Bundle\FixturesBundle\Fixture;
use Doctrine\Persistence\ObjectManager;

use App\Entity\Race;
use App\Entity\CharacterClass;
use App\Entity\Skill;

class AppFixtures extends Fixture
{
    public function load(ObjectManager $manager): void
    {
        // $product = new Product();
        // $manager->persist($product);
        $Race = new Race();
        $Race->setName('Human');
        $Race->setDescription('Polyvalent and ambiscious, the humans are the most common race)');
        $manager->persist($Race);
        $Race = new Race();
        $Race->setName('Elf');
        $Race->setDescription('Graceful and long-lived, elves have a natural affinity for magic');
        $manager->persist($Race);
        $Race = new Race();
        $Race->setName('Dwarf');
        $Race->setDescription('Sturdy and resilient, dwarves are skilled warriors and craftsmen');
        $manager->persist($Race);
        $Race = new Race();
        $Race->setName('Halfling');
        $Race->setDescription('Small and nimble, halflings are known for their luck and stealth');
        $manager->persist($Race);
        $Race = new Race();
        $Race->setName('half-Orc');
        $Race->setDescription('Berserk and fierce, half-orcs combine the strength of orcs with the adaptability of humans');
        $manager->persist($Race);
        $Race = new Race();
        $Race->setName('Gnome');
        $Race->setDescription('Ingenious and curious, gnomes are excellent with magic and technology');
        $manager->persist($Race);
        $Race = new Race();
        $Race->setName('Tiefling');
        $Race->setDescription('Heirs of infernal bloodlines, tieflings bear the mark of their heritage');
        $manager->persist($Race);
        $Race = new Race();
        $Race->setName('Half-Elf');
        $Race->setDescription('Inheritant of the better of both worlds, half-elves are versatile and diplomatic');
        $manager->persist($Race);
        $Class = new CharacterClass();
        $Class->setName('Barbarian');
        $Class->setDescription('Savages warrior animated by a devastating rage');
        $Class->setHealthDice(12);
        $manager->persist($Class);
        $Class = new CharacterClass();
        $Class->setName('Bard');
        $Class->setDescription('Artists and storytellers, bards weave magic through music');
        $Class->setHealthDice(8);
        $manager->persist($Class);
        $Class = new CharacterClass();
        $Class->setName('Cleric');
        $Class->setDescription('Divine spellcasters who serve the gods');
        $Class->setHealthDice(8);
        $manager->persist($Class);
        $Class = new CharacterClass();
        $Class->setName('Druid');
        $Class->setDescription('nature\'s guardian capable of shapeshifting');
        $Class->setHealthDice(8);
        $manager->persist($Class);
        $Class = new CharacterClass();
        $Class->setName('Fighter');
        $Class->setDescription('Skilled combatants who excel in martial combat');
        $Class->setHealthDice(10);
        $manager->persist($Class);
        $Class = new CharacterClass();
        $Class->setName('Mage');
        $Class->setDescription('Erudite arcanist mastering the forces of magic');
        $Class->setHealthDice(6);
        $manager->persist($Class);
        $Class = new CharacterClass();
        $Class->setName('Paladin');
        $Class->setDescription('Holy knight who combine combat prowess with divine magic');
        $Class->setHealthDice(10);
        $manager->persist($Class);
        $Class = new CharacterClass();
        $Class->setName('Ranger');
        $Class->setDescription('Tracker and hunter, expert of wilderness survival');
        $Class->setHealthDice(10);
        $manager->persist($Class);
        $Class = new CharacterClass();
        $Class->setName('Sorcerer');
        $Class->setDescription('Innate spellcasters who wield magic through raw talent');
        $Class->setHealthDice(6);
        $manager->persist($Class);
        $Class = new CharacterClass();
        $Class->setName('Rogue');
        $Class->setDescription('Expert in sthealth, deception and surprise attacks');
        $Class->setHealthDice(8);
        $manager->persist($Class);
        $Skill = new Skill();
        $Skill->setName('Acrobatics');
        $Skill->setAbility('Dexterity');
        $manager->persist($Skill);
        $Skill = new Skill();
        $Skill->setName('Arcana');
        $Skill->setAbility('Intelligence');
        $manager->persist($Skill);
        $Skill = new Skill();
        $Skill->setName('Athletics');
        $Skill->setAbility('Strength');
        $manager->persist($Skill);
        $Skill = new Skill();
        $Skill->setName('Stealth');
        $Skill->setAbility('Dexterity');
        $manager->persist($Skill);
        $Skill = new Skill();
        $Skill->setName('Animal Handling');
        $Skill->setAbility('Wisdom');
        $manager->persist($Skill);
        $Skill = new Skill();
        $Skill->setName('Sleight of Hand');
        $Skill->setAbility('Dexterity');
        $manager->persist($Skill);
        $Skill = new Skill();
        $Skill->setName('History');
        $Skill->setAbility('Intelligence');
        $manager->persist($Skill);
        $Skill = new Skill();
        $Skill->setName('Intimidation');
        $Skill->setAbility('Charisma');
        $manager->persist($Skill);
        $Skill = new Skill();
        $Skill->setName('Investigation');
        $Skill->setAbility('Intelligence');
        $manager->persist($Skill);
        $Skill = new Skill();
        $Skill->setName('Medicine');
        $Skill->setAbility('Wisdom');
        $manager->persist($Skill);
        $Skill = new Skill();
        $Skill->setName('Nature');
        $Skill->setAbility('Intelligence');
        $manager->persist($Skill);
        $Skill = new Skill();
        $Skill->setName('Perception');
        $Skill->setAbility('Wisdom');
        $manager->persist($Skill);
        $Skill = new Skill();
        $Skill->setName('Insight');
        $Skill->setAbility('Wisdom');
        $manager->persist($Skill);
        $Skill = new Skill();
        $Skill->setName('Persuasion');
        $Skill->setAbility('Charisma');
        $manager->persist($Skill);
        $Skill = new Skill();
        $Skill->setName('Religion');
        $Skill->setAbility('Intelligence');
        $manager->persist($Skill);
        $Skill = new Skill();
        $Skill->setName('Performance');
        $Skill->setAbility('Charisma');
        $manager->persist($Skill);
        $Skill = new Skill();
        $Skill->setName('Survival');
        $Skill->setAbility('Wisdom');
        $manager->persist($Skill);
        $Skill = new Skill();
        $Skill->setName('Deception');
        $Skill->setAbility('Charisma');
        $manager->persist($Skill);
        $manager->flush();
    }
}
